#
# SPDX-FileCopyrightText: 2023 Dominik Wombacher <dominik@wombacher.cc>
# SPDX-License-Identifier: CC0-1.0
#
commitizen:
  changelog_incremental: true
  update_changelog_on_bump: true
  name: cz_conventional_commits
  tag_format: $version
  version: 0.1.0
