# SPDX-FileCopyrightText: 2023 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: CC0-1.0

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/moinmoin-pypy2,quay.io/${CI_REPO_OWNER}/moinmoin-pypy2

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: *repo
      dockerfile: *file
      platforms: linux/amd64
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      no_cache: true
      purge: true
      auto_tag: true
      logins:
        - registry: https://codeberg.org
          username: ${CI_REPO_OWNER}
          password:
            from_secret: cb_token_write_package
        - registry: https://quay.io
          username:
            from_secret: quay_user
          password:
          from_secret: quay_pass

